name: Deploy
on:
  push:
    branches: [main]

env:
  NODE_VERSION: "20.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🤖 Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📥 Install deps
        run: npm ci

      - name: 🚧 npm build
        run: npm run build

      - name: 🚀 Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
